name: Python Tests

on:
  pull_request:
      paths:
      - '**.py'
      - '!setup.py'
      - '.github/workflows/test-python.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

jobs:
  build:
    name: Django Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout django-mongodb
        uses: actions/checkout@v4
      - name: install the django-mongodb backend
        run: |
          pip3 install --upgrade pip
          pip3 install -e .
      - name: Checkout Django
        uses: actions/checkout@v4
        with:
          repository: 'mongodb-forks/django'
          ref: 'mongodb-tests1'
          path: 'django_repo'
      - name: Install system packages for Django's Python test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libmemcached-dev
      - name: Install Django and its Python test dependencies
        run: |
          cd django_repo/tests/
          pip3 install -e ..
          pip3 install -r requirements/py3.txt
      - name: Copy the test settings file
        run: cp .github/workflows/mongodb_settings.py django_repo/tests/
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 5.0
      - name: Run tests
        run: >
          python3 django_repo/tests/runtests.py --settings mongodb_settings -v 2
          lookup
          m2m_and_m2o
          m2m_intermediary
          m2m_multiple
          m2m_recursive
          m2m_regress
          m2m_signals
          m2m_through
          m2m_through_regress
          m2o_recursive
          many_to_many
          many_to_one
          many_to_one_null
          migrations
          model_fields
          model_forms
          model_inheritance_regress
          mongo_fields
          mutually_referential
          nested_foreign_keys
          null_fk
          null_fk_ordering
          null_queries
